name: PingSafe CLI Pull Request Scan

on:
  # Triggers the workflow when pull_request created on master/main branch
  pull_request:
    types: [ opened, reopened, synchronize ]
    branches: [ master, main ]

jobs:
  pingsafe-cli:
    runs-on: ubuntu-latest
    container:
      image: pingsafe/cli:latest
      options: --entrypoint ""

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Configure git config
        run: git config --global --add safe.directory $PWD

      - name: Configure PingSafe-CLI
        run: pingsafe-cli config --api-token ${{ secrets.PINGSAFE_TOKEN }}

      - name: Configure git
        run: git config --global --add safe.directory $PWD

      - name: Run Secret Detector
        run:  pingsafe-cli scan secret -d $PWD --pull-request origin/$SRC $DEST
        env:
          DEST: ${{ github.event.pull_request.base.sha }}
          SRC: ${{ github.event.pull_request.head.ref }}


